"use client";

import { useMemo, useState } from "react";

type Choice = { label: string };
type Answers = { goal: string; context: string; zone: string; format: string; duration: string };
const WHATSAPP = "https://wa.me/79994179908";
const MAP_2GIS = "https://2gis.ru/krasnodar/firm/70000001115905481";
const MAP_YANDEX = "https://yandex.ru/maps/org/studiya_massazha_i_sportivnogo_vosstanovleniya/82082580508/";
const steps: Array<{ key: keyof Answers; eyebrow: string; title: string; options: Choice[] }> = [
  { key: "goal", eyebrow: "Шаг 1 из 5 · задача", title: "Что хотите получить от сеанса?", options: ["Восстановиться после спорта или нагрузки", "Снять напряжение в спине и шее", "Расслабиться и перезагрузиться", "Улучшить самочувствие и подвижность", "Уделить внимание лицу", "Подобрать массаж для другого человека", "Пока не знаю, нужна рекомендация"].map((label) => ({ label })) },
  { key: "context", eyebrow: "Шаг 2 из 5 · контекст", title: "Как проходит ваша неделя?", options: ["Регулярные тренировки", "Сидячая работа", "Физическая работа", "Длительная поездка", "Стресс и переутомление", "Подготовка к событию", "Просто хочу расслабиться", "Другое"].map((label) => ({ label })) },
  { key: "zone", eyebrow: "Шаг 3 из 5 · зона", title: "Какая зона вас интересует?", options: ["Всё тело", "Спина и поясница", "Шея и плечи", "Ноги", "Лицо и голова", "Отдельная зона", "Затрудняюсь выбрать"].map((label) => ({ label })) },
  { key: "format", eyebrow: "Шаг 4 из 5 · формат", title: "Где вам удобнее?", options: ["Студия на Хакурате, 12", "Выезд мастера", "Пока не знаю", "Хочу подарочный сертификат"].map((label) => ({ label })) },
  { key: "duration", eyebrow: "Шаг 5 из 5 · время", title: "Сколько времени готовы выделить?", options: ["30–40 минут", "60 минут", "90 минут", "120 минут", "Нужна рекомендация"].map((label) => ({ label })) },
];
const directions = [
  { number: "01", title: "Восстановление после нагрузки", text: "Для тех, кто тренируется или хочет уделить внимание телу после активного дня.", tags: "Спортивный · восстановительный" },
  { number: "02", title: "Расслабление и перезагрузка", text: "Спокойный сценарий, когда хочется замедлиться и переключиться на себя.", tags: "Расслабляющий · классический" },
  { number: "03", title: "Спина и шея", text: "Поможет точнее сформулировать, где ощущается напряжение и какой формат обсудить.", tags: "Классический · восстановительный" },
  { number: "04", title: "Массаж лица и уход", text: "Отдельное внимание лицу — с выбором подходящей техники и длительности перед записью.", tags: "Массаж лица" },
];
const faqs = [
  ["Как выбрать подходящий массаж?", "Пройдите короткий подбор: цель, контекст, зона, формат и длительность. Если сомневаетесь, так и укажите — мастер уточнит детали в WhatsApp."],
  ["Можно ли записаться впервые без знания названия процедуры?", "Да. Необязательно знать название — достаточно описать задачу и ощущения своими словами."],
  ["Есть ли выезд?", "Выездной формат есть. Уточните доступность, район, время и формат процедуры в WhatsApp."],
  ["Можно ли выбрать интенсивность?", "Да, пожелания по интенсивности можно обсудить до записи и перед сеансом."],
  ["Сколько длится сеанс?", "В подборе доступны ориентиры от 30–40 до 120 минут. Точную длительность можно обсудить по задаче."],
  ["Можно ли оформить подарочный сертификат?", "Да, оставьте запрос в WhatsApp — подскажем детали оформления."],
  ["Что сообщить перед первым посещением?", "Расскажите о своей задаче, зоне внимания, желаемой длительности и удобном формате. Также заранее сообщите о важных ограничениях."],
  ["Есть ли противопоказания?", "Массаж не заменяет консультацию врача. При противопоказаниях и сомнениях заранее проконсультируйтесь со специалистом."],
];

export const dynamic = "force-static";

function getRecommendation(answers: Answers) {
  if (answers.goal.includes("спорт")) return { title: "Спортивный или восстановительный массаж", text: "Вам может подойти спортивный или восстановительный массаж. В сообщении укажите вид нагрузки и зоны, которые хочется проработать." };
  if (answers.goal.includes("расслаб")) return { title: "Расслабляющий массаж", text: "Вам может подойти расслабляющий массаж. Можно выбрать студию или уточнить возможность выезда." };
  if (answers.zone.includes("спин") || answers.zone.includes("шея")) return { title: "Массаж спины и шейно-воротниковой зоны", text: "Вам может подойти массаж спины и шейно-воротниковой зоны. Перед записью мастер уточнит ваши ощущения и пожелания по интенсивности." };
  if (answers.goal.includes("лиц") || answers.zone.includes("лиц")) return { title: "Массаж лица", text: "Вам может подойти массаж лица. Уточним подходящую технику и продолжительность перед записью." };
  return { title: "Подходящий формат после короткого уточнения", text: "Подберём формат после короткого уточнения задачи, зоны и желаемой длительности." };
}

export default function Home() {
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Answers>({ goal: "", context: "", zone: "", format: "", duration: "" }); const [showResult, setShowResult] = useState(false); const [sent, setSent] = useState(false); const [details, setDetails] = useState({ name: "", date: "", time: "", comment: "" }); const [locationMode, setLocationMode] = useState<"studio" | "visit">("studio"); const [openFaq, setOpenFaq] = useState<number | null>(0);
  const current = steps[step]; const recommendation = useMemo(() => getRecommendation(answers), [answers]); const hasSelection = Boolean(answers[current.key]);
  const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  const selectAnswer = (value: string) => setAnswers((prev) => ({ ...prev, [current.key]: value }));
  const nextStep = () => { if (!hasSelection) return; if (step === steps.length - 1) setShowResult(true); else setStep((value) => value + 1); };
  const resetWizard = () => { setAnswers({ goal: "", context: "", zone: "", format: "", duration: "" }); setDetails({ name: "", date: "", time: "", comment: "" }); setStep(0); setShowResult(false); setSent(false); };
  const buildMessage = () => `Здравствуйте! Хочу подобрать массаж.\n\nМоя цель: ${answers.goal || "пока не определился(лась)"}\nКонтекст/нагрузка: ${answers.context || "не указано"}\nЗона: ${answers.zone || "не указано"}\nФормат: ${answers.format || "не указано"}\nЖелаемая длительность: ${answers.duration || "не указано"}\nЖелаемая дата: ${details.date || "не указано"}\nУдобное время: ${details.time || "не указано"}\nИмя: ${details.name || "не указано"}${details.comment ? `\nКомментарий: ${details.comment}` : ""}\n\nПодскажите, какой вариант мне подойдёт и есть ли свободное время?`;
  const sendWhatsApp = () => { setSent(true); window.open(`${WHATSAPP}?text=${encodeURIComponent(buildMessage())}`, "_blank", "noopener,noreferrer"); };

  return <main>
    <header className="topbar container"><a className="brand" href="#top" aria-label="Студия массажа и спортивного восстановления"><span className="brand-mark"><i /><i /><i /></span><span>студия<br /><b>восстановления</b></span></a><div className="topbar-actions"><span className="city-label">Краснодар</span><a className="phone-link" href="tel:+79994179908">+7 999 417-99-08</a><a className="whatsapp-link" href={WHATSAPP} target="_blank" rel="noreferrer">WhatsApp <span>↗</span></a></div></header>
    <section className="hero container" id="top"><div className="hero-copy"><p className="kicker"><span className="signal" /> Массаж · спорт · восстановление</p><h1>Массаж под вашу задачу — <em>без угадывания</em> по каталогу</h1><p className="hero-lead">Ответьте на несколько вопросов — подберём подходящий формат массажа и передадим ваш запрос мастеру.</p><div className="hero-actions"><button className="button button-primary" onClick={() => scrollTo("selector")}>Подобрать массаж <span>↘</span></button><a className="button button-ghost" href={WHATSAPP} target="_blank" rel="noreferrer">Написать в WhatsApp <span>↗</span></a></div><div className="hero-facts"><span>Краснодар</span><span>Хакурате, 12</span><span>По предварительной записи</span><span>Студия и выезд</span></div></div><div className="hero-visual"><img className="hero-image" src="./hero-massage-recovery.png" alt="Мужчина-массажист проводит восстановительный массаж в студии" width="1536" height="1024" fetchPriority="high" /></div></section>
    <section className="trust-section container"><div className="section-intro"><p className="kicker">01 / есть вопросы — есть ориентиры</p><h2>Спокойный путь<br /><em>к своему формату</em></h2></div><div className="trust-grid"><div className="trust-card rating-card"><span className="trust-icon">✦</span><div><strong>5,0</strong><span>рейтинг в 2ГИС</span></div><a href={MAP_2GIS} target="_blank" rel="noreferrer">Смотреть карточку <span>↗</span></a></div><div className="trust-card rating-card"><span className="trust-icon">✦</span><div><strong>4,8</strong><span>рейтинг в Яндекс Картах</span></div><a href={MAP_YANDEX} target="_blank" rel="noreferrer">Смотреть карточку <span>↗</span></a></div><div className="trust-card"><span className="trust-icon">◎</span><div><strong>Отзывы</strong><span>реальные впечатления — на картах</span></div><a href={MAP_2GIS} target="_blank" rel="noreferrer">Посмотреть все отзывы <span>↗</span></a></div><div className="trust-card address-card"><span className="trust-icon">⌖</span><div><strong>Хакурате, 12</strong><span>Краснодар · по записи</span></div><a href="https://yandex.ru/maps/?text=Краснодар%20ул.%20Хакурате%2012" target="_blank" rel="noreferrer">Построить маршрут <span>↗</span></a></div></div></section>
    <section className="selector-section container" id="selector"><div className="selector-heading"><div><p className="kicker">02 / подбор формата</p><h2>Соберём ваш<br /><em>запрос за минуту</em></h2></div><p className="heading-note">Пять коротких шагов.<br />Без регистрации и лишних полей.</p></div><div className="wizard-card"><div className="wizard-top"><div className="progress-label">{showResult ? "Готово" : current.eyebrow}</div><div className="progress-bar" aria-label={`Пройдено ${showResult ? 5 : step} из 5`}><span style={{ width: `${showResult ? 100 : (step / steps.length) * 100}%` }} /></div><div className="progress-count">{showResult ? "05" : `0${step + 1}`}<small>/ 05</small></div></div>{!showResult ? <div className="wizard-body"><div className="wizard-question"><h3>{current.title}</h3><p>Можно выбрать один вариант — вернуться и изменить ответ получится в любой момент.</p></div><div className="options-grid">{current.options.map((option) => <button key={option.label} className={`option ${answers[current.key] === option.label ? "selected" : ""}`} onClick={() => selectAnswer(option.label)}><span className="option-dot" /><span>{option.label}</span><b>↗</b></button>)}</div><div className="wizard-controls"><button className="text-button" onClick={() => step > 0 && setStep((value) => value - 1)} disabled={step === 0}>← Назад</button><button className="button button-dark" onClick={nextStep} disabled={!hasSelection}>{step === steps.length - 1 ? "Показать подбор" : "Следующий шаг"} <span>→</span></button></div></div> : <ResultPanel recommendation={recommendation} answers={answers} details={details} setDetails={setDetails} onBack={() => { setShowResult(false); setStep(4); }} onReset={resetWizard} onSend={sendWhatsApp} sent={sent} />}</div>{!showResult && <div className="answer-preview"><span>Ваши ответы</span>{Object.values(answers).map((answer, index) => answer ? <button key={index} onClick={() => setStep(index)}>{answer} <b>×</b></button> : null)}{Object.values(answers).every((answer) => !answer) && <small>Появятся здесь по мере прохождения</small>}</div>}</section>
    <section className="directions-section container"><div className="section-heading-row"><div><p className="kicker">03 / направления</p><h2>Не каталог.<br /><em>Понятные сценарии.</em></h2></div><p>Начните с задачи — название процедуры можно уточнить позже.</p></div><div className="direction-grid">{directions.map((direction) => <article className="direction-card" key={direction.number}><span className="card-number">{direction.number}</span><h3>{direction.title}</h3><p>{direction.text}</p><div className="direction-foot"><span>{direction.tags}</span><button onClick={() => { setStep(0); setShowResult(false); scrollTo("selector"); }}>Подобрать <b>↗</b></button></div></article>)}</div></section>
    <section className="format-section container"><div className="format-panel"><div className="format-copy"><p className="kicker">04 / как проходит визит</p><h2>Выберите место,<br /><em>остальное уточним</em></h2><p>Работаем по предварительной записи. Можно приехать в студию или уточнить доступность выезда в WhatsApp.</p><div className="toggle" role="tablist" aria-label="Формат посещения"><button className={locationMode === "studio" ? "active" : ""} onClick={() => setLocationMode("studio")}>Приехать в студию</button><button className={locationMode === "visit" ? "active" : ""} onClick={() => setLocationMode("visit")}>Уточнить выезд</button></div>{locationMode === "studio" ? <div className="location-details"><strong>Краснодар, ул. Хакурате, 12</strong><span>Студия · по предварительной записи</span><div><a href="https://yandex.ru/maps/?text=Краснодар%20ул.%20Хакурате%2012" target="_blank" rel="noreferrer">Маршрут ↗</a><a href={WHATSAPP} target="_blank" rel="noreferrer">Записаться ↗</a></div></div> : <div className="location-details visit-details"><strong>Уточним возможность выезда</strong><span>Напишите район, желаемое время и формат процедуры.</span><a href={WHATSAPP} target="_blank" rel="noreferrer">Написать в WhatsApp ↗</a></div>}</div><div className="map-widget"><iframe title="Карта студии массажа на Хакурате, 12" src="https://yandex.ru/map-widget/v1/?mode=search&oid=82082580508&ol=biz&z=16" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div></section>
    <section className="reviews-section container"><div className="review-copy"><p className="kicker">05 / доверие без громких обещаний</p><h2>Посмотрите,<br /><em>что говорят клиенты</em></h2><p>Мы не пересказываем отзывы на сайте — все впечатления и актуальная оценка доступны в карточках студии.</p><div className="review-links"><a href={MAP_2GIS} target="_blank" rel="noreferrer"><span>2ГИС</span><b>5,0</b><i>↗</i></a><a href={MAP_YANDEX} target="_blank" rel="noreferrer"><span>Яндекс Карты</span><b>4,8</b><i>↗</i></a></div></div><div className="review-quote"><span className="quote-mark">“</span><p>«Свой формат можно подобрать и без знания названия процедуры.»</p><small>Сценарий студии · без медицинских обещаний</small></div></section>
    <section className="faq-section container"><div><p className="kicker">06 / вопросы</p><h2>Перед первым<br /><em>посещением</em></h2></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? "open" : ""}`} key={question}><button onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index}><span>{question}</span><b>{openFaq === index ? "−" : "+"}</b></button>{openFaq === index && <p>{answer}</p>}</div>)}</div></section>
    <section className="final-cta container"><div><p className="kicker">07 / следующий шаг</p><h2>Опишите задачу —<br /><em>подскажем формат</em></h2><p>Необязательно заранее знать название процедуры. Напишите, чего хотите добиться, какая зона вас интересует и когда вам удобно.</p></div><div className="final-actions"><button className="button button-primary" onClick={() => scrollTo("selector")}>Подобрать массаж <span>↘</span></button><a className="button button-light" href={WHATSAPP} target="_blank" rel="noreferrer">Написать в WhatsApp <span>↗</span></a></div></section>
    <footer className="footer container"><div className="brand"><span className="brand-mark"><i /><i /><i /></span><span>студия<br /><b>восстановления</b></span></div><div className="footer-address">Краснодар, ул. Хакурате, 12<br /><a href="tel:+79994179908">+7 999 417-99-08</a></div><div className="footer-links"><a href={MAP_2GIS} target="_blank" rel="noreferrer">2ГИС ↗</a><a href={MAP_YANDEX} target="_blank" rel="noreferrer">Яндекс Карты ↗</a><a href={WHATSAPP} target="_blank" rel="noreferrer">WhatsApp ↗</a></div><p className="disclaimer">Массаж не заменяет консультацию врача. При противопоказаниях необходимо заранее проконсультироваться со специалистом.</p></footer>
    <button className="mobile-cta" onClick={() => showResult ? sendWhatsApp() : scrollTo("selector")}>{showResult ? "Отправить запрос в WhatsApp" : "Подобрать массаж"}<span>↗</span></button>
  </main>;
}

function ResultPanel({ recommendation, answers, details, setDetails, onBack, onReset, onSend, sent }: { recommendation: { title: string; text: string }; answers: Answers; details: { name: string; date: string; time: string; comment: string }; setDetails: React.Dispatch<React.SetStateAction<{ name: string; date: string; time: string; comment: string }>>; onBack: () => void; onReset: () => void; onSend: () => void; sent: boolean }) {
  const labels: Record<string, string> = { goal: "Цель", context: "Контекст", zone: "Зона", format: "Формат", duration: "Время" };
  return <div className="result-body"><div className="result-intro"><span className="result-badge">Ваш ориентир</span><h3>{recommendation.title}</h3><p>{recommendation.text}</p><div className="result-summary">{Object.entries(answers).map(([key, value]) => <span key={key}><small>{labels[key]}</small>{value}</span>)}</div></div><div className="request-form"><div className="form-heading"><div><span className="kicker">Запрос времени</span><h3>Передать детали в WhatsApp</h3></div><button className="text-button" onClick={onBack}>← Изменить ответы</button></div><div className="form-grid"><label>Имя<input value={details.name} onChange={(event) => setDetails((prev) => ({ ...prev, name: event.target.value }))} placeholder="Как к вам обращаться" /></label><label>Желаемая дата<input type="date" value={details.date} onChange={(event) => setDetails((prev) => ({ ...prev, date: event.target.value }))} /></label><label>Удобное время<input type="time" value={details.time} onChange={(event) => setDetails((prev) => ({ ...prev, time: event.target.value }))} /></label><label className="wide">Комментарий<textarea value={details.comment} onChange={(event) => setDetails((prev) => ({ ...prev, comment: event.target.value }))} placeholder="Например, вид нагрузки или пожелания по интенсивности" rows={3} /></label></div><p className="form-hint">Можно отправить без имени и даты, но эти данные помогут быстрее уточнить свободное время.</p><button className="button button-primary form-submit" onClick={onSend}>Сформировать запрос в WhatsApp <span>↗</span></button>{sent && <div className="sent-message" role="status">Запрос подготовлен. Студия получит ваши данные в WhatsApp и сможет уточнить подходящий формат и свободное время.</div>}<button className="reset-button" onClick={onReset}>Начать подбор заново</button></div></div>;
}
